name: "Registry release listener"
description: "Listens for new releases on registry packages"
inputs:
  token:
    description: "Github Access Token"
    required: true
  gh-name:
    description: "Github account name"
    required: true
  gh-email:
    description: "Github account email"
    required: true

runs:
  using: composite
  steps:
    - name: "Get package registry data"
      uses: actions/checkout@v3
      with:
        repository: swift-nav/package-registry
        token: ${{ inputs.token }}
        ref: main

    - name: "Store name and version env vars"
      shell: bash
      run: |
        echo "NAME=${NAME:-${{ github.event.repository.name }}}" >> $GITHUB_ENV
        echo "VERSION=${VERSION:-${GITHUB_REF##*/}}" >> $GITHUB_ENV
        echo "Stored ${{ env.NAME }} and ${{ env.VERSION }}"

    - name: "Ensures release is not linked"
      shell: bash
      working-directory: data
      run: |
        if cat ${NAME,,} | grep "\"version\":\"${{ env.VERSION }}\""; then
          exit 1
        fi

    - name: Pull gen
      shell: bash
      run: curl https://swiftnav-releases.s3.us-west-2.amazonaws.com/swift-cli/reg-gen -o gen

    - name: "Modify data to link release"
      shell: bash
      env:
        NAME: ${{ env.NAME }}
        VERSION: ${{ env.VERSION }}
      run: gen

    - name: "Create pull request from changes"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        rm gen
        git config --global user.email "${{ inputs.gh-email }}"
        git config --global user.name "${{ inputs.gh-name }}"
        git switch -c "coolbot/update-${{ env.NAME }}-${{ env.VERSION }}"
        git add data
        git commit -m "Updating release for ${{ env.NAME }}-${{ env.VERSION }}"
        git push --set-upstream origin coolbot/update-${{ env.NAME }}-${{ env.VERSION }} -f
        gh pr create \
          --title "Release for ${{ env.NAME }}-${{ env.VERSION }}" \
          --body "Automated registry sync for ${{ env.NAME }} created by tag ${{ env.VERSION }}" \
          --reviewer adrian-kong,isaactorz,silverjam
          
